config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      :sessions => "users/sessions",
      :registrations => "users/registrations"}

  devise_scope :user do
    authenticated :user do
      resources :users
      resources :posts, :only => [:new, :create]
      resources :groups, :only => [:show, :new, :create]
      post "groups/request_join/:id", :to => "groups#request_join", :as => "request_join_group"
      put "groups/accept_join_request/:id/:user_id", :to => "groups#accept_join_request", :as => "accept_join_request"

      root "users#index"
    end
    unauthenticated :user do
      get "/home/faq", to: "home#faq"

      root "devise/sessions#new"
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord

  belongs_to :user

  has_many :group_maps, :dependent => :destroy
  has_many :users, :through => :group_maps


  def is_owner?(user)
    self.user == user
  end

  def is_member?(user)
    self.group_maps.where(:user_id => user).pluck(:status) == :accepted
  end

  def get_users(user)
    if is_owner?(user)
      User.find(self.group_maps.pluck(:user_id)) # this return group ids
    else
      "nope"
    end
  end

  def get_member_status(user)
    self.group_maps.where(:user_id => user).pluck(:status).first
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    # @groups = Group.joins(:group_maps).merge(GroupMap.where(:status => :accepted))
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create

    @group = current_user.groups.build(group_params)
    @group.user = current_user
    @group_map = @group.group_maps.build(:status => :accepted, :user => current_user)

    if @group.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def update

  end

  def destroy

  end

  def request_join
    @group = Group.find(params[:id])
    @group_map = @group.group_maps.build(:status => :waiting, :user => current_user)

    # status kontrolü yapılacak

    if @group_map.save
      redirect_to group_path(@group)
    else
      render 'new'
    end
  end

  def accept_join_request
    @group = Group.find(params[:id])
    @user = User.find(params[:user_id])

    if @group.group_maps.where(:user_id => @user).update(:status => :accepted)
      redirect_to group_path(@group)
    else
      render 'new'
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, :status);
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_index.html.erb
<div class="row pull-left" style="margin: 0;">
  <div class="col-xs-12">
    <i class="fa fa-plus-circle" aria-hidden="true"></i>
    <%= link_to 'create group', new_group_path%>
    <table>
    <% @groups.each do |group| %>
      <tr>
        <td>
          <% if group.is_owner?(current_user) %>
              <i class="fa fa-user" aria-hidden="true"></i>
          <% end %>
        </td>
        <td><%= link_to group.name, group_path(group) %></td>
      </tr>
    <% end %>
    </table>
  </div>
</div>

app/views/groups/new.html.erb
<div class="container">
  <div class="row" style="margin: 0;">
    <div class="col-xs-6 col-xs-offset-3">
      <div class="panel panel-default">
        <div class="panel-body">
          <!--<textarea class="form-control" rows="5" id="comment" placeholder="Write something to share with your mates ..." ></textarea><br/>-->
          <%= form_for @group do |f| %>
              <%= f.text_field :name , :class => "form-control", "placeholder" => "Your very own group's name" %><br/>
              <%= button_tag  "create", :class => "btn btn-primary pull-right" do %>
                  Create
                  <i class="fa fa-users" aria-hidden="true"></i>
              <% end %>
          <% end %>
          <!--<button type="button" class="btn btn-primary pull-right">Share-->
          <!--<span class="glyphicon glyphicon-share-alt"></span></button>-->
          <!--<button type="button" class="btn btn-success pull-right">Upload <span class="glyphicon glyphicon-picture"></span> / <span class="glyphicon glyphicon-facetime-video"></span>-->
          <!--</button>-->
        </div>
      </div>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<%= render 'layouts/top-navigation-bar' %>
<div class="container">
  <div class="col-xs-3">

  </div>
  <div class="col-xs-6">
    <%= @group.name %>
    <% if @group.is_owner?(current_user)%>
      you are the one who FUCKS
        <%= @group.get_member_status(current_user) %>
      <% else %>
        <% if @group.get_member_status(current_user).present? %>
            <%= button_to  @group.get_member_status(current_user), "#" , :class => "btn btn-primary disabled" %>
        <% else %>
            <%= button_to  "Join Group", request_join_group_path(@group) , :class => "btn btn-primary", :method => :post %>
        <% end %>
      hell yeah you are not a fukn owner
    <% end %>
  </div>
  <div class="col-xs-3">
    <div class="col-xs-12 pull-right">
      <table>
        <tr>
          <td>Users list</td>
        </tr>
        <% if @group.is_owner?(current_user) %>
          <% @group.get_users(current_user).each do |user| %>
            <tr>
              <td>
                <%= link_to (user.firstname + " " +  user.lastname), user_path(user) %>
              </td>
              <td>
                <% if @group.get_member_status(user).present? %>
                    <% if @group.get_member_status(user) == "waiting" %>
                      <%= button_to  "Accept", accept_join_request_path(@group, :user_id => user.id) , :class => "btn btn-primary", :method => :put %>
                    <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </table>
    </div>
  </div>
</div>