config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      :sessions => "users/sessions",
      :registrations => "users/registrations"}

  devise_scope :user do
    authenticated :user do
      resources :users
      resources :posts, :only => [:new, :create]
      resources :groups, :only => [:show, :new, :create]
      post "groups/request_join/:id", :to => "groups#request_join", :as => "request_join_group"
      put "groups/accept_join_request/:id/:user_id", :to => "groups#accept_join_request", :as => "accept_join_request"

      root "users#index"
    end
    unauthenticated :user do
      get "/home/faq", to: "home#faq"

      root "devise/sessions#new"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

  def sign_up

  end

  def sign_in

  end

  def faq

  end
  
end

app/helpers/home_helper.rb
module HomeHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/views/home/faq.html.erb
<%= link_to "Sign in", new_user_session_path %>
<%= link_to "Sign in", new_user_registration_path %>
<%= link_to "FAQ", home_faq_path %>
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>

app/views/home/index.html.erb
<!--<p>-->
  <!--<%= link_to "Sign in", new_user_session_path %>-->
  <!--<%= link_to "FAQ", home_faq_path %>-->
  <!--<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>-->
<!--</p>-->
<div id="outer">
<div class="container" id="inner">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3">
      <h2 class="section-title no-margin-top"><%= t('label.user.form_title.register') %></h2>
      <div class="panel panel-primary-dark animated fadeInDown">
        <div class="panel-heading"><%= t('label.user.form_name.register') %></div>
        <div class="panel-body">
          <%= form_for(resource, as: resource_name, :role => "form", url: registration_path(resource_name)) do |f| %>
              <%= devise_error_messages! %>
              <div class="form-group">
                <%= f.label t('label.user.form_content.firstname') %><br/>
                <%= f.text_field :firstname, autofocus: true, :class => "form-control text-center" %>
              </div>
              <div class="form-group">
                <%= f.label t('label.user.form_content.lastname') %><br/>
                <%= f.text_field :lastname, :class => "form-control text-center" %>
              </div>
              <div class="form-group">
                <%= f.label t('label.user.form_content.email') %><br/>
                <%= f.email_field :email, :class => "form-control text-center" %>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <%= f.label t('label.user.form_content.password') %>
                    <% if @minimum_password_length %>
                        <em>(<%= @minimum_password_length %> characters minimum)</em>
                    <% end %><br/>
                    <%= f.password_field :password, autocomplete: "off", :class => "form-control text-center" %>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <%= f.label t('label.user.form_content.password_confirmation') %>
                    <% if @minimum_password_length %>
                        <em>(Must be same with password)</em><br/>
                    <% end %><br/>
                    <%= f.password_field :password_confirmation, autocomplete: "off", :class => "form-control text-center" %>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <div class="btn-group" data-toggle="buttons">
                    <% Role.all.each do |role| %>
                        <label for="first" class="btn btn-primary">
                          <%= f.radio_button :role, role.name, :id => role.name , :style => "display:none;" %><%= role.name %>
                        </label>
                    <% end %>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12 text-center">
                  <div class="checkbox checkbox-inline">
                    <%= f.check_box :terms_of_service %>
                    <label for="inlineCheckbox1"><%= t('label.user.form_content.terms_and_conditions_html', terms_and_conditions_url:"#" )%></label>
                  </div>
                </div>
              </div>
              <br>
              <div class="row">
                <div class="col-md-12 text-center">
                  <%= button_tag t('label.user.form_button.register'), :class => "btn btn-ar btn-primary"%><br>
                </div>
              </div>
              <br>
              <div class="row">
                <div class="col-md-12 text-center">
                  <%- if controller_name != 'sessions' %>
                      <%= link_to t('label.user.form_content.i_already_have_an_account'), new_session_path(resource_name), :class => "pull-right" %>
                  <% end -%>
                </div>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div> <!-- container  -->

</div>

app/views/home/show.html.erb
<p>Home/show HERE!</p>

<%= link_to "Sign in", new_user_session_path %>